// Export all homepage components
export { default as HeroSection } from './HeroSection'
export { default as StatsSection } from './StatsSection'
export { default as HealthCardShowcase } from './HealthCardShowcase'
export { default as HowItWorksSection } from './HowItWorksSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as PricingSection } from './PricingSection'
export { default as BenefitsSection } from './BenefitsSection'
export { default as VideoDemoSection } from './VideoDemoSection'
export { default as TrustedBySection } from './TrustedBySection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as ComparisonSection } from './ComparisonSection'
export { default as FinalCTASection } from './FinalCTASection'
export { default as FAQSection } from './FAQSection'

